import gifMap from "@/data/exercise-gifs.json";
import extraGifMap from "@/data/exercise-gifs-extra.json";
import importGifMap from "@/data/exercise-gifs-import.json";

/**
 * Demo animations.
 *
 * The dataset's original media (a third-party Cloudflare R2 bucket) went dark
 * on 2026-09-05 — every object returns 401 — so the male/female MP4s and
 * posters in exercises.json are dead and deliberately ignored.
 *
 * Three GIF sources, all served over the jsDelivr CDN:
 *
 * 1. omercotkd/exercises-gifs (MIT-labelled mirror of the Kaggle "Fitness
 *    Exercises with Animations" set). Our original ExerciseDB-style numeric
 *    ids match its filenames directly; src/data/exercise-gifs.json is
 *    generated by `npm run build:gif-map`.
 * 2. JahelCuadrado/ExerciseGymGifsDB for exercises the first source lacks.
 *    src/data/exercise-gifs-extra.json is HAND-CURATED: every entry was
 *    matched on name and then visually verified frame-by-frame, because a
 *    wrong demo is worse than none. Values are either a path in that repo or
 *    a full URL (one gif comes from mohamedatef90/exercise-library).
 * 3. hasaneyldrm/exercises-dataset for the ~1000 bulk-imported exercises —
 *    src/data/exercise-gifs-import.json maps id -> "<id>-<media>" gif stems
 *    in that repo's videos/ folder (generated by the import script).
 *
 * Provenance caveat: none of these repos own the animations. Fine for
 * personal use; review the rights and mirror the files to our own storage
 * before shipping commercially.
 */
const CDN = "https://cdn.jsdelivr.net/gh/omercotkd/exercises-gifs@main/assets";
const CDN_EXTRA = "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@main";
const CDN_IMPORT = "https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@main/videos";

const ids: Record<string, string> = gifMap;
const extra: Record<string, string> = extraGifMap;
const imported: Record<string, string> = importGifMap;

/** CDN url for an exercise's demo animation, or null when we have none. */
export function gifUrlFor(exerciseId: string): string | null {
  const gifId = ids[exerciseId];
  if (gifId) return `${CDN}/${gifId}.gif`;
  const extraPath = extra[exerciseId];
  if (extraPath) {
    return extraPath.startsWith("http")
      ? extraPath
      : `${CDN_EXTRA}/${extraPath}.gif`;
  }
  const importStem = imported[exerciseId];
  return importStem ? `${CDN_IMPORT}/${importStem}.gif` : null;
}
